### ISSUE TITLE
Security alert: jquery version to low

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/cardat.github.com#2]
@KarthikGopi1234  @cassandrayuen  

I got a github warning email about

https://github.com/cardat/cardat.github.com/blob/master/data_inventory/libs/jquery-2.2.3/jquery.min.js

```
warning
Known security vulnerabilities detected
Dependency jquery 	Version >= 1.2.0 < 3.5.0 	Upgrade to ~> 3.5.0
Defined in jquery.min.js
```

I think you can just delete that folder as it seems like you also have 

https://github.com/cardat/cardat.github.com/tree/master/data_inventory/libs/jquery-3.6.0

in the libs folder.

**Comment by KarthikGopi1234** [comment]
Folder has been removed from data_inventory/libs
